# Shallow Neural Network in Keras

Build a shallow neural network to classify MNIST digits

#### Set seed for reproducibility

In [194]:
import sys
sys.executable

'C:\\Anaconda3\\envs\\tensorflow\\python.exe'

In [2]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [3]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

C:\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


#### Load data

In [162]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [5]:
X_train.shape

(60000, 28, 28)

In [6]:
y_train.shape

(60000,)

In [7]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [8]:
X_test.shape

(10000, 28, 28)

In [210]:
X_test[1].shape

(28, 28)

In [211]:
X_test[1]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 116, 125, 171,
        255, 255, 150,  93,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 169, 253, 253, 253,
        253, 253, 253, 218,  30,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 169, 253, 253, 253, 213,
        142, 176, 253, 253, 122,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [10]:
y_test.shape

(10000,)

In [11]:
y_test[1]

2

#### Preprocess data

In [12]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [13]:
X_train /= 255
X_test /= 255

In [57]:
X_test[0].shape


(28, 28)

In [59]:
X_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [15]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [16]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

#### Design neural network architecture

In [17]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))

In [18]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [19]:
(64*784)

50176

In [20]:
(64*784)+64

50240

In [21]:
(10*64)+10

650

#### Configure model

In [22]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train!

In [23]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 2s 31us/step - loss: 0.0915 - acc: 0.0895 - val_loss: 0.0911 - val_acc: 0.0955
Epoch 2/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0908 - acc: 0.1058 - val_loss: 0.0905 - val_acc: 0.1162
Epoch 3/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0903 - acc: 0.1406 - val_loss: 0.0901 - val_acc: 0.1513
Epoch 4/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0899 - acc: 0.1925 - val_loss: 0.0897 - val_acc: 0.2058
Epoch 5/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0895 - acc: 0.2401 - val_loss: 0.0893 - val_acc: 0.2424
Epoch 6/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0891 - acc: 0.2706 - val_loss: 0.0889 - val_acc: 0.2715
Epoch 7/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0888 - acc: 0.2905 - val_loss: 0.0886 - 

Epoch 118/200
60000/60000 [==============================] - 2s 36us/step - loss: 0.0435 - acc: 0.7665 - val_loss: 0.0426 - val_acc: 0.7756
Epoch 119/200
60000/60000 [==============================] - 2s 31us/step - loss: 0.0432 - acc: 0.7682 - val_loss: 0.0423 - val_acc: 0.7779
Epoch 120/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0429 - acc: 0.7700 - val_loss: 0.0420 - val_acc: 0.7790
Epoch 121/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0426 - acc: 0.7712 - val_loss: 0.0417 - val_acc: 0.7806
Epoch 122/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0423 - acc: 0.7727 - val_loss: 0.0414 - val_acc: 0.7822
Epoch 123/200
60000/60000 [==============================] - 2s 40us/step - loss: 0.0421 - acc: 0.7746 - val_loss: 0.0411 - val_acc: 0.7849
Epoch 124/200
60000/60000 [==============================] - 2s 38us/step - loss: 0.0418 - acc: 0.7765 - val_loss: 0.0409 - val_acc: 0.7868
Epoch 125/200
60000/

In [24]:
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 0s 43us/step


[0.02717633790373802, 0.8658]

In [25]:
import cv2

In [92]:
#test2 = cv2.imread("test2.jpg")
test2 = cv2.imread("test2.jpg", cv2.cv2.IMREAD_GRAYSCALE)

In [93]:
test2.size

784

In [94]:
test2[1][2]
#test2

255

In [95]:
test2.shape

(28, 28)

In [96]:
resized_image_test2 = cv2.resize(test2, (28, 28)) 

In [97]:
resized_image_test2.size

784

In [102]:
resized_image_test2.shape

(28, 28)

In [112]:
resized_image

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[254, 254, 254],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 254, 254],
        [253, 253, 253],
        [250, 250, 250]],

       [[254, 254, 254],
        [254, 254, 254],
        [252, 252, 252],
        ...,
        [145, 145, 145],
        [252, 252, 252],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [217, 217, 217],
        [251, 251, 251],
        [254, 254, 254]]

In [113]:
resized_image[15][16]

array([252, 252, 252], dtype=uint8)

In [121]:
28*28

784

In [37]:
#newimage = np.resize(x, [28,28])

In [91]:
#newimage

In [109]:
def myfunc(z):
    return abs(z-255)
#a = np.zeros(shape=(28,28))

In [110]:
a.shape

(28, 28)

In [111]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0

In [114]:
#resized_image = resized_image.astype(np.int16)
myfunc = np.vectorize(myfunc, otypes=[np.float])
newA = face.astype(np.int16)
result = myfunc_vec(resized_image_test2)
#result = myfunc_vec(resized_image_test2)
result.size


NameError: name 'face' is not defined

In [115]:
result

array([[  0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,
          1,  36,  96, 102,  73,   1,   0,   0,   3,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 106, 129,
        143,  84,  34,  20, 244,   0,   6,   1,   0,   4,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   4,   0, 120,   1,   4,
          3,   0,   2,   0, 138,  73,   0,   0,   2,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 101,   3,   1,   0,
          1,   3,   0,   0,  17, 242,   1,   0,   0,   3,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 167,   0,   1,   5,
          0,   4,   0,   3,   0, 208,   8,   0,   2,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  10,  21,   0,   0,   0,
          1,   0,   4,   0,   3,  94, 126,   2,   1,   0,   2,   0,   0,
          0,   0],
       [  

In [116]:
result.shape
reshapedimg = result.reshape(1, 784).astype('float32')

model.predict(reshapedimg)


array([[0.034386  , 0.04096843, 0.00063885, 0.01396213, 0.00208418,
        0.10228583, 0.00862515, 0.44929332, 0.00804095, 0.33971515]],
      dtype=float32)

In [122]:
test4 = cv2.imread("test4better.jpg", cv2.cv2.IMREAD_GRAYSCALE)
test4 = cv2.resize(test4, (28, 28)) 
test4.shape
test4

array([[217, 219, 217, 219, 221, 219, 222, 219, 220, 218, 217, 217, 218,
        219, 217, 221, 221, 222, 221, 221, 223, 220, 216, 222, 218, 217,
        218, 219],
       [217, 218, 220, 215, 219, 221, 222, 222, 218, 218, 216, 217, 222,
        221, 219, 219, 216, 221, 218, 222, 220, 217, 221, 218, 216, 213,
        218, 217],
       [219, 216, 217, 219, 218, 219, 220, 219, 219, 218, 215, 219, 221,
        220, 219, 224, 218, 219, 219, 224, 221, 220, 217, 219, 221, 218,
        221, 219],
       [219, 219, 219, 218, 218, 220, 221, 221, 218, 218, 219, 219, 218,
        221, 221, 218, 217, 218, 216, 219, 219, 221, 219, 219, 221, 219,
        219, 222],
       [220, 219, 220, 221, 217, 219, 222, 219, 220, 218, 217, 217, 215,
        220, 218, 219, 218, 217, 218, 217, 218, 217, 226, 218, 222, 219,
        220, 221],
       [216, 217, 219, 217, 217, 217, 219, 219, 218, 218, 219, 220, 220,
        220, 220, 218, 220, 220, 216, 219, 219, 221, 221, 219, 223, 218,
        219, 220],
       [21

In [125]:
result = myfunc_vec(test4)
reshapedimg = result.reshape(1, 784).astype('float32')
reshapedimg /= 255

In [126]:
reshapedimg

array([[0.14901961, 0.14117648, 0.14901961, 0.14117648, 0.13333334,
        0.14117648, 0.12941177, 0.14117648, 0.13725491, 0.14509805,
        0.14901961, 0.14901961, 0.14509805, 0.14117648, 0.14901961,
        0.13333334, 0.13333334, 0.12941177, 0.13333334, 0.13333334,
        0.1254902 , 0.13725491, 0.15294118, 0.12941177, 0.14509805,
        0.14901961, 0.14509805, 0.14117648, 0.14901961, 0.14509805,
        0.13725491, 0.15686275, 0.14117648, 0.13333334, 0.12941177,
        0.12941177, 0.14509805, 0.14509805, 0.15294118, 0.14901961,
        0.12941177, 0.13333334, 0.14117648, 0.14117648, 0.15294118,
        0.13333334, 0.14509805, 0.12941177, 0.13725491, 0.14901961,
        0.13333334, 0.14509805, 0.15294118, 0.16470589, 0.14509805,
        0.14901961, 0.14117648, 0.15294118, 0.14901961, 0.14117648,
        0.14509805, 0.14117648, 0.13725491, 0.14117648, 0.14117648,
        0.14509805, 0.15686275, 0.14117648, 0.13333334, 0.13725491,
        0.14117648, 0.12156863, 0.14509805, 0.14

In [146]:
def invert(z):
    return abs(z-255)

def brighten(z):
    if(z<100):
        return 0.0
    else:
        return z
#a = np.zeros(shape=(28,28))

In [159]:
#test4 = cv2.imread("test4.jpg", cv2.cv2.IMREAD_GRAYSCALE)
#test4 = cv2.resize(test4, (28, 28)) 
#invert = np.vectorize(invert, otypes=[np.float])
#test4 = invert(test4)
#brighten = np.vectorize(brighten, otypes=[np.float])
#test4 = brighten(test4)
reshapedimg = test4.reshape(1, 784).astype('float32')
#
reshapedimg /= 255
reshapedimg
result = model.predict(reshapedimg)
#n_classes = 10
#keras.utils.to_categorical(result, n_classes)

array([[0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00173779, 0.00195309,
        0.00213764, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00229143, 0.0021684 , 0.00236832, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00

In [164]:
test4 = invert(test4)
#cv2.imwrite("/Temp/test4.bmp",test4)
cv2.imwrite("/Temp/testsetnum.bmp",X_test[1])

True

In [176]:
#X_test[1]
#test4 = test4.astype(np.uint8)
#test4
reshapedimg = test4.reshape(1, 784).astype('float32')
reshapedimg /= 255
reshapedimg
result = model.predict(reshapedimg)
result
#n_classes = 10
#keras.utils.to_categorical(result, n_classes)

#test4 = invert(test4)
#test4

array([[0.12673727, 0.01990256, 0.08104635, 0.08354645, 0.20915388,
        0.2006497 , 0.05133255, 0.08735745, 0.05018364, 0.09009027]],
      dtype=float32)

In [192]:
resultArray = np.asarray(result[0])
resultArray.tolist().index(max(result[0]))

4

In [174]:
test4 = test4.astype(np.uint8)
test4

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0, 142, 128, 116,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 106, 114, 101,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 102, 141, 159, 125, 107,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 108, 142, 156, 113,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0, 151, 165, 137, 112,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 113, 193, 156,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 107, 171, 183, 167, 119,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 129, 193, 174,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 113, 183, 188, 144,   0,   0,   0,
          0,   0],
       [  

In [193]:
test4 = cv2.imread("test4.jpg", cv2.cv2.IMREAD_GRAYSCALE)
test4 = cv2.resize(test4, (28, 28)) 
invert = np.vectorize(invert, otypes=[np.float])
test4 = invert(test4)
brighten = np.vectorize(brighten, otypes=[np.float])
test4 = brighten(test4)
reshapedimg = test4.reshape(1, 784).astype('float32')
reshapedimg /= 255
result = model.predict(reshapedimg)
resultArray = np.asarray(result[0])
resultArray.tolist().index(max(result[0]))

4

In [240]:
def invert(z):
    return abs(z-255)

def brighten(z):
    if(z<130):
        return 0.0
    if(z>150):
        return 255.0
    else:
        return z
test8 = cv2.imread("test2.jpg", cv2.cv2.IMREAD_GRAYSCALE)
test8 = cv2.resize(test8, (28, 28)) 
invert = np.vectorize(invert, otypes=[np.float])
test8 = invert(test8)
brighten = np.vectorize(brighten, otypes=[np.float])
test8 = brighten(test8)
test8 = X_test[3]
#test8=test8.astype(np.uint8)
cv2.imwrite("/Temp/testsetnum.bmp",test8)
reshapedimg = test8.reshape(1, 784).astype('float32')
reshapedimg /= 255
result = model.predict(reshapedimg)
resultArray = np.asarray(result[0])
resultArray.tolist().index(max(result[0]))
#result

0

In [228]:
test8

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 166.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 134.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0

In [229]:
X_test[1]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 116, 125, 171,
        255, 255, 150,  93,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 169, 253, 253, 253,
        253, 253, 253, 218,  30,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 169, 253, 253, 253, 213,
        142, 176, 253, 253, 122,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [198]:
test8 = cv2.imread("test8.jpg", cv2.cv2.IMREAD_GRAYSCALE)

In [200]:
test8 = cv2.resize(test4, (28, 28)) 

In [221]:
cv2.imwrite("/Temp/testsetnum2.bmp",X_test[1])

True

In [202]:
invert = np.vectorize(invert, otypes=[np.float])

In [203]:
test8 = invert(test8)

In [205]:
brighten = np.vectorize(brighten, otypes=[np.float])
test8 = brighten(test8)

In [214]:
reshapedimg = test8.reshape(1, 784).astype('float32')


In [216]:
reshapedimg /= 255
result = model.predict(reshapedimg)

In [217]:
result

array([[0.20979929, 0.00931124, 0.11923025, 0.10231639, 0.02885046,
        0.221767  , 0.03390548, 0.04421921, 0.15973018, 0.07087056]],
      dtype=float32)