[View in Colaboratory](https://colab.research.google.com/github/hackaton-advisors/jupyter/blob/master/shallow_net_in_keras.ipynb)

# Shallow Neural Network in Keras

Build a shallow neural network to classify MNIST digits

#### Set seed for reproducibility

In [41]:
import sys
sys.executable

'/usr/bin/python3'

In [42]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [43]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

# Install a Drive FUSE wrapper.
# https://github.com/astrada/google-drive-ocamlfuse
!apt-get update -qq 2>&1 > /dev/null
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse


gpg: keybox '/tmp/tmpjoqvz240/pubring.gpg' created
gpg: /tmp/tmpjoqvz240/trustdb.gpg: trustdb created
gpg: key AD5F235DF639B041: public key "Launchpad PPA for Alessandro Strada" imported
gpg: Total number processed: 1
gpg:               imported: 1


#### Load data

In [119]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [120]:
X_train.shape

(60000, 28, 28)

In [46]:
# Generate auth tokens for Colab
from google.colab import auth
auth.authenticate_user()

# Generate creds for the Drive FUSE library.
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
# Work around misordering of STREAM and STDIN in Jupyter.
# https://github.com/jupyter/notebook/issues/3159
prompt = !google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass(prompt[0] + '\n\nEnter verification code: ')
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}


IndexError: ignored

In [5]:
# Create a directory and mount Google Drive using that directory.
!mkdir -p drive
!google-drive-ocamlfuse drive



# Create a file in Drive.
!echo "This newly created file will appear in your Drive file list." > drive/villecreated.txt

Files in Drive:
010c__havainnekuvin.odt
12113A käännös.odt
12113B_no.doc
12113B_no.doc.odt
12452.doc
12452.doc.odt
12847-en.doc.odt
12847 lyhyt.doc
15yr mortgage.ods
1st Grade Class Lists.pdf
2007 Rave Benefits Summary (updated version).odt
2007 Rave Benefits Summary (updated version).odt (3391ee62)
2007 Rave Benefits Summary (updated version).odt (c8c85caf)
2017Resume.odt
446
446.pdf
9592 rakennettavuusselvitys.odt
amtrakaugust 2009 travelexpensereportus1.ods
Annan suostumukseni siihen, että oma ....odt
Annaprasana of AKD4.pdf
backpackthesierra.odt
backpackthesierra.pdf
berkeley-questions.odt
Bicycling directions to Mile High Cafe, California 243, Idyllwild-Pine Cove, CA.desktop
BlackCanyon16
box store -1702 McGaw Ave.desktop
bu.ods
California
capresume.odt
Celebration of Gabe's Life.docx
C-JDBC_Solutions_Linux_2004.pdf
cloudcroft Shared route
Colab Notebooks
colorado
ConciseResume.odt
Configuration management:.odt
Copy of 12113A käännös.odt
Copy of 12113B_no.doc.odt
Copy of capresume

In [10]:
print('Files in Drive:')
!ls drive/

Files in Drive:
010c__havainnekuvin.odt
12113A käännös.odt
12113B_no.doc
12113B_no.doc.odt
12452.doc
12452.doc.odt
12847-en.doc.odt
12847 lyhyt.doc
15yr mortgage.ods
1st Grade Class Lists.pdf
2007 Rave Benefits Summary (updated version).odt
2007 Rave Benefits Summary (updated version).odt (3391ee62)
2007 Rave Benefits Summary (updated version).odt (c8c85caf)
2017Resume.odt
446
446.pdf
9592 rakennettavuusselvitys.odt
amtrakaugust 2009 travelexpensereportus1.ods
Annan suostumukseni siihen, että oma ....odt
Annaprasana of AKD4.pdf
backpackthesierra.odt
backpackthesierra.pdf
berkeley-questions.odt
Bicycling directions to Mile High Cafe, California 243, Idyllwild-Pine Cove, CA.desktop
BlackCanyon16
box store -1702 McGaw Ave.desktop
bu.ods
California
capresume.odt
Celebration of Gabe's Life.docx
C-JDBC_Solutions_Linux_2004.pdf
cloudcroft Shared route
Colab Notebooks
colorado
ConciseResume.odt
Configuration management:.odt
Copy of 12113A käännös.odt
Copy of 12113B_no.doc.odt
Copy of capresume

In [89]:
y_train.shape

(60000,)

In [90]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [91]:
X_test.shape

(10000, 28, 28)

In [92]:
X_test[1].shape

(28, 28)

In [93]:
X_test[1]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 116, 125, 171,
        255, 255, 150,  93,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 169, 253, 253, 253,
        253, 253, 253, 218,  30,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 169, 253, 253, 253, 213,
        142, 176, 253, 253, 122,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [0]:
y_test.shape

(10000,)

In [0]:
y_test[1]

2

#### Preprocess data

In [121]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [122]:
X_train /= 255
X_test /= 255

In [123]:
X_test[0].shape


(784,)

In [124]:
X_test[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [125]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [126]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

#### Design neural network architecture

In [127]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))

In [128]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_4 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [0]:
(64*784)

50176

In [0]:
(64*784)+64

50240

In [0]:
(10*64)+10

650

#### Configure model

In [129]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train!

In [131]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))
model.save("drive/numberModel")
#reshapedimg = X_test[5].reshape(1, 784).astype('float32')

#reshapedimg /= 255
result = model.predict(X_test[5],batch_size=1)
result
#resultArray = np.asarray(result[0])
#resultArray.tolist().index(max(result[0]))
#reshapedimg


Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 2s 25us/step - loss: 0.0832 - acc: 0.3938 - val_loss: 0.0829 - val_acc: 0.4003
Epoch 2/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0828 - acc: 0.3984 - val_loss: 0.0825 - val_acc: 0.4040
Epoch 3/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0824 - acc: 0.4022 - val_loss: 0.0820 - val_acc: 0.4072
Epoch 4/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0819 - acc: 0.4060 - val_loss: 0.0816 - val_acc: 0.4103
Epoch 5/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0815 - acc: 0.4094 - val_loss: 0.0811 - val_acc: 0.4130
Epoch 6/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0810 - acc: 0.4133 - val_loss: 0.0807 - val_acc: 0.4166
Epoch 7/200
 1920/60000 [..............................]

60000/60000 [==============================] - 2s 29us/step - loss: 0.0806 - acc: 0.4172 - val_loss: 0.0802 - val_acc: 0.4191
Epoch 8/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0801 - acc: 0.4217 - val_loss: 0.0797 - val_acc: 0.4221
Epoch 9/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0796 - acc: 0.4257 - val_loss: 0.0792 - val_acc: 0.4270
Epoch 10/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0791 - acc: 0.4302 - val_loss: 0.0787 - val_acc: 0.4315
Epoch 11/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0786 - acc: 0.4350 - val_loss: 0.0782 - val_acc: 0.4376
Epoch 12/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0781 - acc: 0.4406 - val_loss: 0.0777 - val_acc: 0.4429
Epoch 13/200
35200/60000 [================>.............] - ETA: 0s - loss: 0.0779 - acc: 0.4406

60000/60000 [==============================] - 2s 28us/step - loss: 0.0776 - acc: 0.4449 - val_loss: 0.0772 - val_acc: 0.4471
Epoch 14/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0771 - acc: 0.4496 - val_loss: 0.0767 - val_acc: 0.4511
Epoch 15/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0766 - acc: 0.4535 - val_loss: 0.0762 - val_acc: 0.4565
Epoch 16/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0761 - acc: 0.4582 - val_loss: 0.0757 - val_acc: 0.4623
Epoch 17/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0756 - acc: 0.4635 - val_loss: 0.0752 - val_acc: 0.4662
Epoch 18/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0751 - acc: 0.4691 - val_loss: 0.0746 - val_acc: 0.4721
Epoch 19/200
41344/60000 [===================>..........] - ETA: 0s - loss: 0.0747 - acc: 0.4721

60000/60000 [==============================] - 2s 28us/step - loss: 0.0746 - acc: 0.4736 - val_loss: 0.0741 - val_acc: 0.4763
Epoch 20/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0741 - acc: 0.4787 - val_loss: 0.0736 - val_acc: 0.4817
Epoch 21/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0735 - acc: 0.4850 - val_loss: 0.0731 - val_acc: 0.4868
Epoch 22/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0730 - acc: 0.4892 - val_loss: 0.0726 - val_acc: 0.4913
Epoch 23/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0725 - acc: 0.4941 - val_loss: 0.0720 - val_acc: 0.4964
Epoch 24/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0720 - acc: 0.4997 - val_loss: 0.0715 - val_acc: 0.5022
Epoch 25/200
34176/60000 [================>.............] - ETA: 0s - loss: 0.0715 - acc: 0.5063

60000/60000 [==============================] - 2s 29us/step - loss: 0.0715 - acc: 0.5042 - val_loss: 0.0710 - val_acc: 0.5075
Epoch 26/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0710 - acc: 0.5097 - val_loss: 0.0705 - val_acc: 0.5125
Epoch 27/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0705 - acc: 0.5150 - val_loss: 0.0700 - val_acc: 0.5174
Epoch 28/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0700 - acc: 0.5193 - val_loss: 0.0694 - val_acc: 0.5224
Epoch 29/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0695 - acc: 0.5244 - val_loss: 0.0689 - val_acc: 0.5260
Epoch 30/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0689 - acc: 0.5288 - val_loss: 0.0684 - val_acc: 0.5307
Epoch 31/200
36480/60000 [=================>............] - ETA: 0s - loss: 0.0685 - acc: 0.5347

60000/60000 [==============================] - 2s 28us/step - loss: 0.0685 - acc: 0.5336 - val_loss: 0.0679 - val_acc: 0.5372
Epoch 32/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0680 - acc: 0.5380 - val_loss: 0.0674 - val_acc: 0.5422
Epoch 33/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0675 - acc: 0.5424 - val_loss: 0.0669 - val_acc: 0.5465
Epoch 34/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0670 - acc: 0.5470 - val_loss: 0.0665 - val_acc: 0.5512
Epoch 35/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0665 - acc: 0.5515 - val_loss: 0.0660 - val_acc: 0.5563
Epoch 36/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0660 - acc: 0.5554 - val_loss: 0.0655 - val_acc: 0.5601
Epoch 37/200
30464/60000 [==============>...............] - ETA: 0s - loss: 0.0656 - acc: 0.5577

60000/60000 [==============================] - 2s 28us/step - loss: 0.0655 - acc: 0.5600 - val_loss: 0.0650 - val_acc: 0.5653
Epoch 38/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0651 - acc: 0.5647 - val_loss: 0.0645 - val_acc: 0.5688
Epoch 39/200
60000/60000 [==============================] - 2s 31us/step - loss: 0.0646 - acc: 0.5686 - val_loss: 0.0641 - val_acc: 0.5733
Epoch 40/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0642 - acc: 0.5733 - val_loss: 0.0636 - val_acc: 0.5772
Epoch 41/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0637 - acc: 0.5780 - val_loss: 0.0631 - val_acc: 0.5814
Epoch 42/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0632 - acc: 0.5823 - val_loss: 0.0627 - val_acc: 0.5866
Epoch 43/200
25216/60000 [===========>..................] - ETA: 0s - loss: 0.0629 - acc: 0.5872

60000/60000 [==============================] - 2s 28us/step - loss: 0.0628 - acc: 0.5864 - val_loss: 0.0622 - val_acc: 0.5909
Epoch 44/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0624 - acc: 0.5904 - val_loss: 0.0618 - val_acc: 0.5958
Epoch 45/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0619 - acc: 0.5940 - val_loss: 0.0614 - val_acc: 0.6019
Epoch 46/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0615 - acc: 0.5979 - val_loss: 0.0609 - val_acc: 0.6051
Epoch 47/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0611 - acc: 0.6019 - val_loss: 0.0605 - val_acc: 0.6080
Epoch 48/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0606 - acc: 0.6051 - val_loss: 0.0601 - val_acc: 0.6115
Epoch 49/200
32384/60000 [===============>..............] - ETA: 0s - loss: 0.0603 - acc: 0.6080

60000/60000 [==============================] - 2s 29us/step - loss: 0.0602 - acc: 0.6091 - val_loss: 0.0596 - val_acc: 0.6149
Epoch 50/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0598 - acc: 0.6121 - val_loss: 0.0592 - val_acc: 0.6181
Epoch 51/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0594 - acc: 0.6153 - val_loss: 0.0588 - val_acc: 0.6216
Epoch 52/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0590 - acc: 0.6188 - val_loss: 0.0584 - val_acc: 0.6242
Epoch 53/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0586 - acc: 0.6226 - val_loss: 0.0580 - val_acc: 0.6269
Epoch 54/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0582 - acc: 0.6255 - val_loss: 0.0576 - val_acc: 0.6289
Epoch 55/200
34432/60000 [================>.............] - ETA: 0s - loss: 0.0579 - acc: 0.6288

60000/60000 [==============================] - 2s 27us/step - loss: 0.0578 - acc: 0.6288 - val_loss: 0.0572 - val_acc: 0.6325
Epoch 56/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0574 - acc: 0.6316 - val_loss: 0.0568 - val_acc: 0.6353
Epoch 57/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0570 - acc: 0.6346 - val_loss: 0.0564 - val_acc: 0.6384
Epoch 58/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0566 - acc: 0.6374 - val_loss: 0.0560 - val_acc: 0.6418
Epoch 59/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0563 - acc: 0.6400 - val_loss: 0.0557 - val_acc: 0.6447
Epoch 60/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0559 - acc: 0.6430 - val_loss: 0.0553 - val_acc: 0.6476
Epoch 61/200
38912/60000 [==================>...........] - ETA: 0s - loss: 0.0555 - acc: 0.6458

60000/60000 [==============================] - 2s 27us/step - loss: 0.0555 - acc: 0.6460 - val_loss: 0.0549 - val_acc: 0.6508
Epoch 62/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0552 - acc: 0.6486 - val_loss: 0.0545 - val_acc: 0.6544
Epoch 63/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0548 - acc: 0.6514 - val_loss: 0.0542 - val_acc: 0.6573
Epoch 64/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0544 - acc: 0.6540 - val_loss: 0.0538 - val_acc: 0.6588
Epoch 65/200
60000/60000 [==============================] - 2s 31us/step - loss: 0.0541 - acc: 0.6559 - val_loss: 0.0535 - val_acc: 0.6619
Epoch 66/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0537 - acc: 0.6581 - val_loss: 0.0531 - val_acc: 0.6656
Epoch 67/200
28928/60000 [=============>................] - ETA: 0s - loss: 0.0536 - acc: 0.6591

60000/60000 [==============================] - 2s 28us/step - loss: 0.0534 - acc: 0.6608 - val_loss: 0.0527 - val_acc: 0.6677
Epoch 68/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0530 - acc: 0.6628 - val_loss: 0.0524 - val_acc: 0.6696
Epoch 69/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0527 - acc: 0.6653 - val_loss: 0.0521 - val_acc: 0.6729
Epoch 70/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0524 - acc: 0.6674 - val_loss: 0.0517 - val_acc: 0.6742
Epoch 71/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0520 - acc: 0.6694 - val_loss: 0.0514 - val_acc: 0.6762
Epoch 72/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0517 - acc: 0.6715 - val_loss: 0.0510 - val_acc: 0.6785
Epoch 73/200
33664/60000 [===============>..............] - ETA: 0s - loss: 0.0515 - acc: 0.6742

60000/60000 [==============================] - 2s 28us/step - loss: 0.0514 - acc: 0.6738 - val_loss: 0.0507 - val_acc: 0.6810
Epoch 74/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0510 - acc: 0.6754 - val_loss: 0.0504 - val_acc: 0.6829
Epoch 75/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0507 - acc: 0.6782 - val_loss: 0.0501 - val_acc: 0.6851
Epoch 76/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0504 - acc: 0.6799 - val_loss: 0.0498 - val_acc: 0.6876
Epoch 77/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0501 - acc: 0.6818 - val_loss: 0.0494 - val_acc: 0.6901
Epoch 78/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0498 - acc: 0.6840 - val_loss: 0.0491 - val_acc: 0.6925
Epoch 79/200
39552/60000 [==================>...........] - ETA: 0s - loss: 0.0495 - acc: 0.6866

60000/60000 [==============================] - 2s 27us/step - loss: 0.0495 - acc: 0.6860 - val_loss: 0.0488 - val_acc: 0.6950
Epoch 80/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0492 - acc: 0.6883 - val_loss: 0.0485 - val_acc: 0.6967
Epoch 81/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0489 - acc: 0.6905 - val_loss: 0.0482 - val_acc: 0.6989
Epoch 82/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0486 - acc: 0.6930 - val_loss: 0.0479 - val_acc: 0.7004
Epoch 83/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0483 - acc: 0.6947 - val_loss: 0.0476 - val_acc: 0.7041
Epoch 84/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0480 - acc: 0.6968 - val_loss: 0.0473 - val_acc: 0.7055
Epoch 85/200
34944/60000 [================>.............] - ETA: 0s - loss: 0.0478 - acc: 0.6973

60000/60000 [==============================] - 2s 28us/step - loss: 0.0477 - acc: 0.6990 - val_loss: 0.0470 - val_acc: 0.7072
Epoch 86/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0474 - acc: 0.7018 - val_loss: 0.0467 - val_acc: 0.7095
Epoch 87/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0471 - acc: 0.7037 - val_loss: 0.0464 - val_acc: 0.7124
Epoch 88/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0468 - acc: 0.7064 - val_loss: 0.0462 - val_acc: 0.7146
Epoch 89/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0466 - acc: 0.7090 - val_loss: 0.0459 - val_acc: 0.7160
Epoch 90/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0463 - acc: 0.7114 - val_loss: 0.0456 - val_acc: 0.7190
Epoch 91/200
33408/60000 [===============>..............] - ETA: 0s - loss: 0.0463 - acc: 0.7124

60000/60000 [==============================] - 2s 30us/step - loss: 0.0460 - acc: 0.7146 - val_loss: 0.0453 - val_acc: 0.7227
Epoch 92/200
60000/60000 [==============================] - 2s 32us/step - loss: 0.0457 - acc: 0.7167 - val_loss: 0.0450 - val_acc: 0.7268
Epoch 93/200
60000/60000 [==============================] - 2s 32us/step - loss: 0.0455 - acc: 0.7199 - val_loss: 0.0448 - val_acc: 0.7294
Epoch 94/200
60000/60000 [==============================] - 2s 31us/step - loss: 0.0452 - acc: 0.7223 - val_loss: 0.0445 - val_acc: 0.7315
Epoch 95/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0449 - acc: 0.7241 - val_loss: 0.0442 - val_acc: 0.7334
Epoch 96/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0447 - acc: 0.7268 - val_loss: 0.0440 - val_acc: 0.7363
Epoch 97/200
25984/60000 [===========>..................] - ETA: 0s - loss: 0.0445 - acc: 0.7269

60000/60000 [==============================] - 2s 28us/step - loss: 0.0444 - acc: 0.7296 - val_loss: 0.0437 - val_acc: 0.7387
Epoch 98/200
60000/60000 [==============================] - 2s 30us/step - loss: 0.0442 - acc: 0.7319 - val_loss: 0.0435 - val_acc: 0.7421
Epoch 99/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0439 - acc: 0.7343 - val_loss: 0.0432 - val_acc: 0.7443
Epoch 100/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0437 - acc: 0.7366 - val_loss: 0.0429 - val_acc: 0.7469
Epoch 101/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0434 - acc: 0.7392 - val_loss: 0.0427 - val_acc: 0.7496
Epoch 102/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0432 - acc: 0.7414 - val_loss: 0.0424 - val_acc: 0.7521
Epoch 103/200
33792/60000 [===============>..............] - ETA: 0s - loss: 0.0431 - acc: 0.7420

60000/60000 [==============================] - 2s 28us/step - loss: 0.0429 - acc: 0.7436 - val_loss: 0.0422 - val_acc: 0.7550
Epoch 104/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0427 - acc: 0.7457 - val_loss: 0.0420 - val_acc: 0.7566
Epoch 105/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0424 - acc: 0.7478 - val_loss: 0.0417 - val_acc: 0.7579
Epoch 106/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0422 - acc: 0.7504 - val_loss: 0.0415 - val_acc: 0.7597
Epoch 107/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0420 - acc: 0.7525 - val_loss: 0.0412 - val_acc: 0.7620
Epoch 108/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0417 - acc: 0.7548 - val_loss: 0.0410 - val_acc: 0.7639
Epoch 109/200
39424/60000 [==================>...........] - ETA: 0s - loss: 0.0416 - acc: 0.7541

60000/60000 [==============================] - 2s 27us/step - loss: 0.0415 - acc: 0.7566 - val_loss: 0.0408 - val_acc: 0.7656
Epoch 110/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0413 - acc: 0.7593 - val_loss: 0.0405 - val_acc: 0.7671
Epoch 111/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0411 - acc: 0.7611 - val_loss: 0.0403 - val_acc: 0.7691
Epoch 112/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0408 - acc: 0.7626 - val_loss: 0.0401 - val_acc: 0.7710
Epoch 113/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0406 - acc: 0.7652 - val_loss: 0.0399 - val_acc: 0.7732
Epoch 114/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0404 - acc: 0.7672 - val_loss: 0.0396 - val_acc: 0.7752
Epoch 115/200
47232/60000 [======================>.......] - ETA: 0s - loss: 0.0403 - acc: 0.7676

60000/60000 [==============================] - 2s 27us/step - loss: 0.0402 - acc: 0.7693 - val_loss: 0.0394 - val_acc: 0.7770
Epoch 116/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0400 - acc: 0.7711 - val_loss: 0.0392 - val_acc: 0.7785
Epoch 117/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0397 - acc: 0.7733 - val_loss: 0.0390 - val_acc: 0.7797
Epoch 118/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0395 - acc: 0.7752 - val_loss: 0.0388 - val_acc: 0.7817
Epoch 119/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0393 - acc: 0.7780 - val_loss: 0.0385 - val_acc: 0.7835
Epoch 120/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0391 - acc: 0.7796 - val_loss: 0.0383 - val_acc: 0.7853
Epoch 121/200
41216/60000 [===================>..........] - ETA: 0s - loss: 0.0390 - acc: 0.7800

60000/60000 [==============================] - 2s 26us/step - loss: 0.0389 - acc: 0.7812 - val_loss: 0.0381 - val_acc: 0.7875
Epoch 122/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0387 - acc: 0.7832 - val_loss: 0.0379 - val_acc: 0.7897
Epoch 123/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0385 - acc: 0.7851 - val_loss: 0.0377 - val_acc: 0.7921
Epoch 124/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0383 - acc: 0.7869 - val_loss: 0.0375 - val_acc: 0.7941
Epoch 125/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0381 - acc: 0.7892 - val_loss: 0.0373 - val_acc: 0.7963
Epoch 126/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0379 - acc: 0.7914 - val_loss: 0.0371 - val_acc: 0.7994
Epoch 127/200
47104/60000 [======================>.......] - ETA: 0s - loss: 0.0376 - acc: 0.7933

60000/60000 [==============================] - 2s 26us/step - loss: 0.0377 - acc: 0.7930 - val_loss: 0.0369 - val_acc: 0.8006
Epoch 128/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0375 - acc: 0.7952 - val_loss: 0.0367 - val_acc: 0.8023
Epoch 129/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0373 - acc: 0.7965 - val_loss: 0.0365 - val_acc: 0.8039
Epoch 130/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0371 - acc: 0.7989 - val_loss: 0.0363 - val_acc: 0.8063
Epoch 131/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0369 - acc: 0.8007 - val_loss: 0.0361 - val_acc: 0.8088
Epoch 132/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0367 - acc: 0.8023 - val_loss: 0.0359 - val_acc: 0.8113
Epoch 133/200
45824/60000 [=====================>........] - ETA: 0s - loss: 0.0364 - acc: 0.8051

60000/60000 [==============================] - 2s 27us/step - loss: 0.0366 - acc: 0.8042 - val_loss: 0.0357 - val_acc: 0.8135
Epoch 134/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0364 - acc: 0.8057 - val_loss: 0.0356 - val_acc: 0.8149
Epoch 135/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0362 - acc: 0.8074 - val_loss: 0.0354 - val_acc: 0.8166
Epoch 136/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0360 - acc: 0.8090 - val_loss: 0.0352 - val_acc: 0.8187
Epoch 137/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0358 - acc: 0.8108 - val_loss: 0.0350 - val_acc: 0.8205
Epoch 138/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0356 - acc: 0.8120 - val_loss: 0.0348 - val_acc: 0.8219
Epoch 139/200
37632/60000 [=================>............] - ETA: 0s - loss: 0.0356 - acc: 0.8124

60000/60000 [==============================] - 2s 28us/step - loss: 0.0355 - acc: 0.8138 - val_loss: 0.0347 - val_acc: 0.8243
Epoch 140/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0353 - acc: 0.8154 - val_loss: 0.0345 - val_acc: 0.8256
Epoch 141/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0351 - acc: 0.8165 - val_loss: 0.0343 - val_acc: 0.8270
Epoch 142/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0350 - acc: 0.8178 - val_loss: 0.0341 - val_acc: 0.8286
Epoch 143/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0348 - acc: 0.8191 - val_loss: 0.0340 - val_acc: 0.8301
Epoch 144/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0346 - acc: 0.8206 - val_loss: 0.0338 - val_acc: 0.8308
Epoch 145/200
40960/60000 [===================>..........] - ETA: 0s - loss: 0.0344 - acc: 0.8213

60000/60000 [==============================] - 2s 27us/step - loss: 0.0344 - acc: 0.8221 - val_loss: 0.0336 - val_acc: 0.8327
Epoch 146/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0343 - acc: 0.8236 - val_loss: 0.0334 - val_acc: 0.8336
Epoch 147/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0341 - acc: 0.8245 - val_loss: 0.0333 - val_acc: 0.8352
Epoch 148/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0340 - acc: 0.8260 - val_loss: 0.0331 - val_acc: 0.8372
Epoch 149/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0338 - acc: 0.8275 - val_loss: 0.0330 - val_acc: 0.8381
Epoch 150/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0336 - acc: 0.8283 - val_loss: 0.0328 - val_acc: 0.8390
Epoch 151/200
42112/60000 [====================>.........] - ETA: 0s - loss: 0.0336 - acc: 0.8284

60000/60000 [==============================] - 2s 27us/step - loss: 0.0335 - acc: 0.8298 - val_loss: 0.0326 - val_acc: 0.8402
Epoch 152/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0333 - acc: 0.8307 - val_loss: 0.0325 - val_acc: 0.8411
Epoch 153/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0332 - acc: 0.8316 - val_loss: 0.0323 - val_acc: 0.8421
Epoch 154/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0330 - acc: 0.8327 - val_loss: 0.0322 - val_acc: 0.8438
Epoch 155/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0329 - acc: 0.8336 - val_loss: 0.0320 - val_acc: 0.8449
Epoch 156/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0327 - acc: 0.8345 - val_loss: 0.0319 - val_acc: 0.8458
Epoch 157/200
44544/60000 [=====================>........] - ETA: 0s - loss: 0.0326 - acc: 0.8354

60000/60000 [==============================] - 2s 26us/step - loss: 0.0326 - acc: 0.8355 - val_loss: 0.0317 - val_acc: 0.8467
Epoch 158/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0324 - acc: 0.8363 - val_loss: 0.0316 - val_acc: 0.8479
Epoch 159/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0323 - acc: 0.8372 - val_loss: 0.0314 - val_acc: 0.8485
Epoch 160/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0321 - acc: 0.8381 - val_loss: 0.0313 - val_acc: 0.8498
Epoch 161/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0320 - acc: 0.8391 - val_loss: 0.0311 - val_acc: 0.8507
Epoch 162/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0318 - acc: 0.8399 - val_loss: 0.0310 - val_acc: 0.8514
Epoch 163/200
39936/60000 [==================>...........] - ETA: 0s - loss: 0.0317 - acc: 0.8416

60000/60000 [==============================] - 2s 28us/step - loss: 0.0317 - acc: 0.8410 - val_loss: 0.0308 - val_acc: 0.8526
Epoch 164/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0316 - acc: 0.8420 - val_loss: 0.0307 - val_acc: 0.8535
Epoch 165/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0314 - acc: 0.8426 - val_loss: 0.0305 - val_acc: 0.8541
Epoch 166/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0313 - acc: 0.8435 - val_loss: 0.0304 - val_acc: 0.8543
Epoch 167/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0312 - acc: 0.8439 - val_loss: 0.0303 - val_acc: 0.8553
Epoch 168/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0310 - acc: 0.8449 - val_loss: 0.0301 - val_acc: 0.8565
Epoch 169/200
35456/60000 [================>.............] - ETA: 0s - loss: 0.0310 - acc: 0.8445

60000/60000 [==============================] - 2s 28us/step - loss: 0.0309 - acc: 0.8453 - val_loss: 0.0300 - val_acc: 0.8567
Epoch 170/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0308 - acc: 0.8460 - val_loss: 0.0299 - val_acc: 0.8572
Epoch 171/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0306 - acc: 0.8468 - val_loss: 0.0297 - val_acc: 0.8581
Epoch 172/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0305 - acc: 0.8474 - val_loss: 0.0296 - val_acc: 0.8588
Epoch 173/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0304 - acc: 0.8482 - val_loss: 0.0295 - val_acc: 0.8597
Epoch 174/200
60000/60000 [==============================] - 2s 29us/step - loss: 0.0303 - acc: 0.8485 - val_loss: 0.0294 - val_acc: 0.8605
Epoch 175/200
33920/60000 [===============>..............] - ETA: 0s - loss: 0.0303 - acc: 0.8489

60000/60000 [==============================] - 2s 27us/step - loss: 0.0301 - acc: 0.8495 - val_loss: 0.0292 - val_acc: 0.8610
Epoch 176/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0300 - acc: 0.8500 - val_loss: 0.0291 - val_acc: 0.8616
Epoch 177/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0299 - acc: 0.8505 - val_loss: 0.0290 - val_acc: 0.8618
Epoch 178/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0298 - acc: 0.8508 - val_loss: 0.0289 - val_acc: 0.8625
Epoch 179/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0296 - acc: 0.8514 - val_loss: 0.0287 - val_acc: 0.8627
Epoch 180/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0295 - acc: 0.8519 - val_loss: 0.0286 - val_acc: 0.8636
Epoch 181/200
47360/60000 [======================>.......] - ETA: 0s - loss: 0.0293 - acc: 0.8531

60000/60000 [==============================] - 2s 26us/step - loss: 0.0294 - acc: 0.8526 - val_loss: 0.0285 - val_acc: 0.8639
Epoch 182/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0293 - acc: 0.8528 - val_loss: 0.0284 - val_acc: 0.8639
Epoch 183/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0292 - acc: 0.8535 - val_loss: 0.0283 - val_acc: 0.8645
Epoch 184/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0291 - acc: 0.8540 - val_loss: 0.0282 - val_acc: 0.8646
Epoch 185/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0290 - acc: 0.8544 - val_loss: 0.0280 - val_acc: 0.8648
Epoch 186/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0288 - acc: 0.8549 - val_loss: 0.0279 - val_acc: 0.8651
Epoch 187/200
48640/60000 [=======================>......] - ETA: 0s - loss: 0.0287 - acc: 0.8553

60000/60000 [==============================] - 2s 26us/step - loss: 0.0287 - acc: 0.8554 - val_loss: 0.0278 - val_acc: 0.8652
Epoch 188/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0286 - acc: 0.8560 - val_loss: 0.0277 - val_acc: 0.8657
Epoch 189/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0285 - acc: 0.8563 - val_loss: 0.0276 - val_acc: 0.8660
Epoch 190/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0284 - acc: 0.8566 - val_loss: 0.0275 - val_acc: 0.8665
Epoch 191/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0283 - acc: 0.8572 - val_loss: 0.0274 - val_acc: 0.8670
Epoch 192/200
60000/60000 [==============================] - 2s 28us/step - loss: 0.0282 - acc: 0.8576 - val_loss: 0.0273 - val_acc: 0.8669
Epoch 193/200
40704/60000 [===================>..........] - ETA: 0s - loss: 0.0282 - acc: 0.8569

60000/60000 [==============================] - 2s 27us/step - loss: 0.0281 - acc: 0.8580 - val_loss: 0.0272 - val_acc: 0.8674
Epoch 194/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0280 - acc: 0.8584 - val_loss: 0.0271 - val_acc: 0.8675
Epoch 195/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0279 - acc: 0.8586 - val_loss: 0.0270 - val_acc: 0.8681
Epoch 196/200
60000/60000 [==============================] - 2s 26us/step - loss: 0.0278 - acc: 0.8591 - val_loss: 0.0269 - val_acc: 0.8687
Epoch 197/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0277 - acc: 0.8594 - val_loss: 0.0268 - val_acc: 0.8691
Epoch 198/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0276 - acc: 0.8596 - val_loss: 0.0267 - val_acc: 0.8696
Epoch 199/200
45056/60000 [=====================>........] - ETA: 0s - loss: 0.0277 - acc: 0.8586

60000/60000 [==============================] - 2s 27us/step - loss: 0.0275 - acc: 0.8601 - val_loss: 0.0266 - val_acc: 0.8699
Epoch 200/200
60000/60000 [==============================] - 2s 27us/step - loss: 0.0274 - acc: 0.8604 - val_loss: 0.0265 - val_acc: 0.8701


ValueError: ignored

In [151]:
model = keras.models.load_model("drive/numberModel")

In [145]:
X_test[5].shape

(784,)

In [153]:
model = keras.models.load_model("drive/numberModel")
test_item = X_test[5].reshape(1, 784).astype('float32')
result = model.predict(test_item)
result

array([[0.00098566, 0.88181424, 0.01852677, 0.02414856, 0.00332271,
        0.01339199, 0.00313626, 0.01338676, 0.02982836, 0.01145862]],
      dtype=float32)

In [115]:
model.evaluate(X_test, y_test)

RuntimeError: ignored

In [7]:
import cv2

In [17]:
#test8 = cv2.imread("number8.jpg")
test8 = cv2.imread("drive/number8.jpg", cv2.cv2.IMREAD_GRAYSCALE)
print(test8)

[[162 163 163 ... 164 164 167]
 [159 161 163 ... 165 164 166]
 [160 160 162 ... 165 163 165]
 ...
 [134 134 133 ... 126 126 128]
 [133 133 131 ... 127 127 129]
 [131 130 129 ... 128 128 130]]


In [15]:
!pwd

/content


In [18]:
test8.size

455040

In [0]:
test2[1][2]
#test2

255

In [0]:
test2.shape

(28, 28)

In [0]:
resized_image_test2.size

784

In [23]:
resized_image= cv2.resize(test8, (28, 28)) 

In [24]:
resized_image.shape

(28, 28)

In [25]:
resized_image

array([[166, 160, 162, 159, 160, 160, 160, 162, 164, 162, 164, 161, 164,
        160, 158, 156, 160, 162, 164, 165, 164, 166, 162, 165, 165, 162,
        167, 166],
       [162, 161, 160, 160, 158, 158, 158, 160, 163, 162, 163, 160, 160,
        162, 157, 159, 162, 165, 162, 163, 164, 165, 166, 168, 159, 164,
        163, 163],
       [162, 161, 159, 157, 160, 160, 162, 164, 166, 164, 165, 162, 164,
        164, 163, 162, 162, 162, 158, 159, 152, 169, 162, 161, 160, 164,
        163, 165],
       [160, 158, 157, 159, 159, 156, 161, 161, 163, 161, 161, 161, 162,
        163, 161, 165, 163, 164, 160,  89, 163, 161, 163, 161, 160, 163,
        164, 165],
       [156, 157, 157, 159, 157, 159, 160, 163, 161, 162, 158, 163, 162,
        157, 162, 163, 160, 164, 136, 121, 162, 156, 165, 165, 161, 160,
        165, 163],
       [157, 156, 158, 159, 158, 160, 161, 161, 163, 161, 162, 164, 163,
        158, 166, 157, 146, 145,  82, 163, 167, 159, 164, 164, 160, 163,
        165, 165],
       [16

In [26]:
resized_image[15][16]

67

In [27]:
28*28

784

In [0]:
#newimage = np.resize(x, [28,28])

In [0]:
#newimage

In [34]:
def myfunc(z):
    return abs(z-255)
#a = np.zeros(shape=(28,28))

In [0]:
a.shape

(28, 28)

In [0]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0

In [39]:
#resized_image = resized_image.astype(np.int16)
#import scipy.misc
face = scipy.misc.face()
def myfunc(z):
    return abs(z-255)
myfunc = np.vectorize(myfunc, otypes=[np.float])
newA = face.astype(np.int16)
myfunc_vec = np.vectorize(myfunc)
result = myfunc_vec(resized_image)
#result = myfunc_vec(resized_image_test2)
result.size


784

In [51]:
result

array([[ 89.,  95.,  93.,  96.,  95.,  95.,  95.,  93.,  91.,  93.,  91.,
         94.,  91.,  95.,  97.,  99.,  95.,  93.,  91.,  90.,  91.,  89.,
         93.,  90.,  90.,  93.,  88.,  89.],
       [ 93.,  94.,  95.,  95.,  97.,  97.,  97.,  95.,  92.,  93.,  92.,
         95.,  95.,  93.,  98.,  96.,  93.,  90.,  93.,  92.,  91.,  90.,
         89.,  87.,  96.,  91.,  92.,  92.],
       [ 93.,  94.,  96.,  98.,  95.,  95.,  93.,  91.,  89.,  91.,  90.,
         93.,  91.,  91.,  92.,  93.,  93.,  93.,  97.,  96., 103.,  86.,
         93.,  94.,  95.,  91.,  92.,  90.],
       [ 95.,  97.,  98.,  96.,  96.,  99.,  94.,  94.,  92.,  94.,  94.,
         94.,  93.,  92.,  94.,  90.,  92.,  91.,  95., 166.,  92.,  94.,
         92.,  94.,  95.,  92.,  91.,  90.],
       [ 99.,  98.,  98.,  96.,  98.,  96.,  95.,  92.,  94.,  93.,  97.,
         92.,  93.,  98.,  93.,  92.,  95.,  91., 119., 134.,  93.,  99.,
         90.,  90.,  94.,  95.,  90.,  92.],
       [ 98.,  99.,  97.,  96.,  97

In [50]:
result.shape
reshapedimg = result.reshape(1, 784).astype('float32')
reshapedimg
#model.predict(reshapedimg)


array([[ 89.,  95.,  93.,  96.,  95.,  95.,  95.,  93.,  91.,  93.,  91.,
         94.,  91.,  95.,  97.,  99.,  95.,  93.,  91.,  90.,  91.,  89.,
         93.,  90.,  90.,  93.,  88.,  89.,  93.,  94.,  95.,  95.,  97.,
         97.,  97.,  95.,  92.,  93.,  92.,  95.,  95.,  93.,  98.,  96.,
         93.,  90.,  93.,  92.,  91.,  90.,  89.,  87.,  96.,  91.,  92.,
         92.,  93.,  94.,  96.,  98.,  95.,  95.,  93.,  91.,  89.,  91.,
         90.,  93.,  91.,  91.,  92.,  93.,  93.,  93.,  97.,  96., 103.,
         86.,  93.,  94.,  95.,  91.,  92.,  90.,  95.,  97.,  98.,  96.,
         96.,  99.,  94.,  94.,  92.,  94.,  94.,  94.,  93.,  92.,  94.,
         90.,  92.,  91.,  95., 166.,  92.,  94.,  92.,  94.,  95.,  92.,
         91.,  90.,  99.,  98.,  98.,  96.,  98.,  96.,  95.,  92.,  94.,
         93.,  97.,  92.,  93.,  98.,  93.,  92.,  95.,  91., 119., 134.,
         93.,  99.,  90.,  90.,  94.,  95.,  90.,  92.,  98.,  99.,  97.,
         96.,  97.,  95.,  94.,  94., 

In [28]:
test8 = cv2.imread("drive/number8.jpg", cv2.cv2.IMREAD_GRAYSCALE)
test8 = cv2.resize(test8, (28, 28)) 
test8.shape
test8

array([[166, 160, 162, 159, 160, 160, 160, 162, 164, 162, 164, 161, 164,
        160, 158, 156, 160, 162, 164, 165, 164, 166, 162, 165, 165, 162,
        167, 166],
       [162, 161, 160, 160, 158, 158, 158, 160, 163, 162, 163, 160, 160,
        162, 157, 159, 162, 165, 162, 163, 164, 165, 166, 168, 159, 164,
        163, 163],
       [162, 161, 159, 157, 160, 160, 162, 164, 166, 164, 165, 162, 164,
        164, 163, 162, 162, 162, 158, 159, 152, 169, 162, 161, 160, 164,
        163, 165],
       [160, 158, 157, 159, 159, 156, 161, 161, 163, 161, 161, 161, 162,
        163, 161, 165, 163, 164, 160,  89, 163, 161, 163, 161, 160, 163,
        164, 165],
       [156, 157, 157, 159, 157, 159, 160, 163, 161, 162, 158, 163, 162,
        157, 162, 163, 160, 164, 136, 121, 162, 156, 165, 165, 161, 160,
        165, 163],
       [157, 156, 158, 159, 158, 160, 161, 161, 163, 161, 162, 164, 163,
        158, 166, 157, 146, 145,  82, 163, 167, 159, 164, 164, 160, 163,
        165, 165],
       [16

In [52]:
result = myfunc_vec(test8)
reshapedimg = result.reshape(1, 784).astype('float32')
reshapedimg /= 255

In [0]:
reshapedimg

array([[0.14901961, 0.14117648, 0.14901961, 0.14117648, 0.13333334,
        0.14117648, 0.12941177, 0.14117648, 0.13725491, 0.14509805,
        0.14901961, 0.14901961, 0.14509805, 0.14117648, 0.14901961,
        0.13333334, 0.13333334, 0.12941177, 0.13333334, 0.13333334,
        0.1254902 , 0.13725491, 0.15294118, 0.12941177, 0.14509805,
        0.14901961, 0.14509805, 0.14117648, 0.14901961, 0.14509805,
        0.13725491, 0.15686275, 0.14117648, 0.13333334, 0.12941177,
        0.12941177, 0.14509805, 0.14509805, 0.15294118, 0.14901961,
        0.12941177, 0.13333334, 0.14117648, 0.14117648, 0.15294118,
        0.13333334, 0.14509805, 0.12941177, 0.13725491, 0.14901961,
        0.13333334, 0.14509805, 0.15294118, 0.16470589, 0.14509805,
        0.14901961, 0.14117648, 0.15294118, 0.14901961, 0.14117648,
        0.14509805, 0.14117648, 0.13725491, 0.14117648, 0.14117648,
        0.14509805, 0.15686275, 0.14117648, 0.13333334, 0.13725491,
        0.14117648, 0.12156863, 0.14509805, 0.14

In [0]:
def invert(z):
    return abs(z-255)

def brighten(z):
    if(z<100):
        return 0.0
    else:
        return z
#a = np.zeros(shape=(28,28))

In [0]:
#test4 = cv2.imread("test4.jpg", cv2.cv2.IMREAD_GRAYSCALE)
#test4 = cv2.resize(test4, (28, 28)) 
#invert = np.vectorize(invert, otypes=[np.float])
#test4 = invert(test4)
#brighten = np.vectorize(brighten, otypes=[np.float])
#test4 = brighten(test4)
reshapedimg = test4.reshape(1, 784).astype('float32')
#
reshapedimg /= 255
reshapedimg
result = model.predict(reshapedimg)
#n_classes = 10
#keras.utils.to_categorical(result, n_classes)

array([[0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00173779, 0.00195309,
        0.00213764, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00229143, 0.0021684 , 0.00236832, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00392157, 0.00392157,
        0.00392157, 0.00392157, 0.00392157, 0.00

In [58]:
result = model.predict(reshapedimg)
result

array([[0.11504813, 0.10483529, 0.08095919, 0.03392908, 0.15166551,
        0.19713983, 0.03848398, 0.0961139 , 0.08815534, 0.09366971]],
      dtype=float32)

In [56]:
def invert(z):
    return abs(z-255)
invert = np.vectorize(invert, otypes=[np.float])
test8 = invert(test8)
cv2.imwrite("/Drive/testsetnum.bmp",test8)

False

In [0]:
#X_test[1]
#test4 = test4.astype(np.uint8)
#test4
reshapedimg = test4.reshape(1, 784).astype('float32')
reshapedimg /= 255
reshapedimg
result = model.predict(reshapedimg)
result
#n_classes = 10
#keras.utils.to_categorical(result, n_classes)

#test4 = invert(test4)
#test4

array([[0.12673727, 0.01990256, 0.08104635, 0.08354645, 0.20915388,
        0.2006497 , 0.05133255, 0.08735745, 0.05018364, 0.09009027]],
      dtype=float32)

In [0]:
resultArray = np.asarray(result[0])
resultArray.tolist().index(max(result[0]))

4

In [0]:
test4 = test4.astype(np.uint8)
test4

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0, 142, 128, 116,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 106, 114, 101,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 102, 141, 159, 125, 107,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 108, 142, 156, 113,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0, 151, 165, 137, 112,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 113, 193, 156,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 107, 171, 183, 167, 119,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 129, 193, 174,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 113, 183, 188, 144,   0,   0,   0,
          0,   0],
       [  

In [0]:
test4 = cv2.imread("test4.jpg", cv2.cv2.IMREAD_GRAYSCALE)
test4 = cv2.resize(test4, (28, 28)) 
invert = np.vectorize(invert, otypes=[np.float])
test4 = invert(test4)
brighten = np.vectorize(brighten, otypes=[np.float])
test4 = brighten(test4)
reshapedimg = test4.reshape(1, 784).astype('float32')
reshapedimg /= 255
result = model.predict(reshapedimg)
resultArray = np.asarray(result[0])
resultArray.tolist().index(max(result[0]))

4

In [0]:
def invert(z):
    return abs(z-255)
invert_vec = np.vectorize(invert, otypes=[np.float])
def brighten(z):
    if(z<130):
        return 0.0
    if(z>150):
        return 255.0
    else:
        return z
test8 = cv2.imread("test2.jpg", cv2.cv2.IMREAD_GRAYSCALE)
test8 = cv2.resize(test8, (28, 28)) 
invert = np.vectorize(invert, otypes=[np.float])
test8 = invert(test8)
brighten = np.vectorize(brighten, otypes=[np.float])
test8 = brighten(test8)
test8 = X_test[3]
#test8=test8.astype(np.uint8)
cv2.imwrite("/Temp/testsetnum.bmp",test8)
reshapedimg = test8.reshape(1, 784).astype('float32')
reshapedimg /= 255
result = model.predict(reshapedimg)
resultArray = np.asarray(result[0])
resultArray.tolist().index(max(result[0]))
#result

0

In [0]:
test8

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 166.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 134.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0

In [88]:
#X_test[1]   cv2.imwrite("drive/testsetnum2.bmp",X_test[1])
reshapedimg = X_test[1].reshape(1, 784).astype('float32')

reshapedimg /= 255
result = model.predict(reshapedimg)

#result = model.predict(X_test[1])
result

array([[0.09048344, 0.11299986, 0.06805648, 0.0363975 , 0.17078878,
        0.21243227, 0.03925431, 0.11154913, 0.08747695, 0.07056123]],
      dtype=float32)

In [0]:
test8 = cv2.imread("test8.jpg", cv2.cv2.IMREAD_GRAYSCALE)

In [0]:
test8 = cv2.resize(test4, (28, 28)) 

In [87]:
cv2.imwrite("drive/testsetnum2.bmp",X_test[1])

True

In [0]:
invert = np.vectorize(invert, otypes=[np.float])

In [0]:
test8 = invert(test8)

In [0]:
brighten = np.vectorize(brighten, otypes=[np.float])
test8 = brighten(test8)

In [0]:
reshapedimg = test8.reshape(1, 784).astype('float32')


In [0]:
reshapedimg /= 255
result = model.predict(reshapedimg)

In [0]:
result

array([[0.20979929, 0.00931124, 0.11923025, 0.10231639, 0.02885046,
        0.221767  , 0.03390548, 0.04421921, 0.15973018, 0.07087056]],
      dtype=float32)

**STARTING FRESH GOOGLE DRIVE NUMBER 8 TEST**

In [162]:
test8 = cv2.imread("drive/number8.jpg", cv2.cv2.IMREAD_GRAYSCALE)
#test8 = cv2.resize(test8, (28, 28)) 
#test8.shape
test8

array([[162, 163, 163, ..., 164, 164, 167],
       [159, 161, 163, ..., 165, 164, 166],
       [160, 160, 162, ..., 165, 163, 165],
       ...,
       [134, 134, 133, ..., 126, 126, 128],
       [133, 133, 131, ..., 127, 127, 129],
       [131, 130, 129, ..., 128, 128, 130]], dtype=uint8)

In [74]:
test8

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       ...,
       [134., 134., 133., ..., 126., 126., 128.],
       [133., 133., 131., ..., 127., 127., 129.],
       [131., 130., 129., ..., 128., 128., 130.]])

In [61]:
cv2.imwrite("drive/initialRead.bmp",test8)

True

In [163]:
def invert(z):
    return abs(z-255)
invert = np.vectorize(invert, otypes=[np.float])

def brighten(z):
    if(z<100):
        return 0.0
    if(z>120):
        return 255.0
    else:
        return z
brighten = np.vectorize(brighten, otypes=[np.float])


#test8 = cv2.imread("test2.jpg", cv2.cv2.IMREAD_GRAYSCALE)
#test8 = cv2.resize(test8, (28, 28)) 
#invert = np.vectorize(invert, otypes=[np.float])
#test8 = invert(test8)
#brighten = np.vectorize(brighten, otypes=[np.float])
#test8 = brighten(test8)
#test8 = X_test[3]
#test8=test8.astype(np.uint8)
#cv2.imwrite("/Temp/testsetnum.bmp",test8)
#reshapedimg = test8.reshape(1, 784).astype('float32')
#reshapedimg /= 255
#result = model.predict(reshapedimg)
#resultArray = np.asarray(result[0])
#resultArray.tolist().index(max(result[0]))

In [165]:
test8 = cv2.resize(test8, (28, 28)) 
cv2.imwrite("drive/afterResize.bmp",test8)

True

In [166]:
test8 = brighten(test8)
cv2.imwrite("drive/afterBrighten.bmp",test8)

True

In [167]:
X_test[1].shape == test8.shape

False

In [0]:
X_test[1]

In [85]:
X_test[1]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 116, 125, 171,
        255, 255, 150,  93,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 169, 253, 253, 253,
        253, 253, 253, 218,  30,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 169, 253, 253, 253, 213,
        142, 176, 253, 253, 122,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [171]:
test8 = invert(test8)
cv2.imwrite("drive/afterInvert.bmp",test8)

True

In [103]:
cv2.imwrite("drive/xtest1.bmp",X_test[1])
print(y_test[1])
cv2.imwrite("drive/xtest2.bmp",X_test[2])
print(y_test[2])
cv2.imwrite("drive/xtest3.bmp",X_test[3])
print(y_test[3])
cv2.imwrite("drive/xtest4.bmp",X_test[4])
print(y_test[4])
cv2.imwrite("drive/xtest5.bmp",X_test[5])
print(y_test[5])
cv2.imwrite("drive/xtest6.bmp",X_test[6])
print(y_test[6])

2
1
0
4
1
4


In [160]:
model = keras.models.load_model("drive/numberModel")
test_item = X_test[4].reshape(1, 784).astype('float32')
result = model.predict(test_item)
result

array([[0.01396552, 0.00236517, 0.04502108, 0.00540804, 0.59070915,
        0.02656973, 0.03823817, 0.05701685, 0.02016097, 0.20054534]],
      dtype=float32)

In [174]:
resultArray = np.asarray(result[0])
resultArray.tolist().index(max(result[0]))

8

In [172]:
test8

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 255.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0

In [173]:
reshapedimg = test8.reshape(1, 784).astype('float32')

reshapedimg /= 255
result = model.predict(reshapedimg,batch_size=1)
result
#resultArray = np.asarray(result[0])
#resultArray.tolist().index(max(result[0]))
#reshapedimg


array([[0.01302565, 0.17004663, 0.04450403, 0.12755741, 0.05662548,
        0.19996311, 0.09104463, 0.01206093, 0.23275936, 0.05241282]],
      dtype=float32)

In [99]:
y_test[4]

4

In [169]:
result

array([[0.37262315, 0.0005062 , 0.3953729 , 0.02133707, 0.01774011,
        0.08782062, 0.01360968, 0.02920977, 0.05212717, 0.00965332]],
      dtype=float32)

In [113]:
y_prob = model.predict(reshapedimg) 
y_classes = y_prob.argmax(axis=-1)
y_classes

array([5])